[package]
name = "mattermost"
version = "0.1.0"
authors = ["Robin Mattheussen <robin.mattheussen@gmail.com>"]
edition = "2018"

[dependencies]
mattermost-http = { path = "../mattermost-http" }
futures = "0.3.7"
tokio = { version = "0.2", features = ["full"] }
